---

- name: Provision Vistoq
  hosts: localhost
  vars:
    ansible_ssh_user: vistoq
    ansible_ssh_pass: vistoq123
    ansible_sudo_pass: vistoq123
  connection: local
  become: true

  tasks:
  - name: Install dependancies
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
      - git
      - python-pip
      - qemu-kvm
      - libvirt-bin
      - python-libvirt
      - salt-minion
      - vim

  - name: Create login banner
    template:
      src: templates/issue
      dest: /etc/issue

  - name: Create salt-minion config
    template:
      src: templates/salt-minion.conf
      dest: /etc/salt/minion

  - name: zero out minion_id
    shell: cat /dev/null > /etc/salt/minion_id

  - name: Set authorized key
    authorized_key:
      user: vistoq
      state: present
      key: "{{ lookup('file', 'templates/authorized_key.pub') }}"

