version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ./compute-node/packer.json
    build-base:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build base
          command: chmod +x ./scripts/build.sh && ./scripts/build.sh compute-node ./compuste-node/packer.json
          no_output_timeout: 30m
      - persist_to_workspace:
          root: .
          paths:
            - manifest-compute-node.json
      - store_artifacts:
          path: build-results
          destination: build-results

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          requires:
            - validate
