version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.2.5
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: chmod +x ./scripts/validate.sh && ./scripts/validate.sh packer vistoq-compute
  build-base:
    docker:
      - image: hashicorp/packer:1.2.5
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build base
          command: chmod +x ./scripts/build.sh && ./scripts/build.sh packer vistoq-compute
          no_output_timeout: 30m
      - store_artifacts:
          path: build-results
          destination: build-results

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          requires:
            - validate
