version: '3'
services:
  bootstrapper:
    image: "nembery/panos_bootstrapper:latest"
    ports:
    - "5000:5000"

  provisioner:
    image: "nembery/salt-master:latest"
    ports:
    - "4505:4505"
    - "4506:4506"
    - "9000:9000"
    volumes:
     - ./provisioner/config:/etc/salt/master.d
     - ./provisioner/salt:/srv/salt
     - ./provisioner/pki:/var/lib/salt/pki/master
     - ./provisioner/pki:/etc/salt/pki/master
     - ./provisioner/run:/var/run/salt

  aframe:
    image: "nembery/aframe:v1.4.8"
    ports:
     - "8080:8000"
    volumes:
     - ./aframe:/app/aframe/conf/imports

  vistoq:
    image: "paloaltonetworks/vistoq:v0.1"
    ports:
      - "80:5000"
